//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Des_BataClub.ws_bataclub {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bataclub.com.pe/", ConfigurationName="ws_bataclub.WS_BataClubSoap")]
    public interface WS_BataClubSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ws_conexionRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://bataclub.com.pe/ws_conexion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Win_Des_BataClub.ws_bataclub.ws_conexionResponse ws_conexion(Win_Des_BataClub.ws_bataclub.ws_conexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bataclub.com.pe/ws_conexion", ReplyAction="*")]
        System.Threading.Tasks.Task<Win_Des_BataClub.ws_bataclub.ws_conexionResponse> ws_conexionAsync(Win_Des_BataClub.ws_bataclub.ws_conexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bataclub.com.pe/ws_genera_cupon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Win_Des_BataClub.ws_bataclub.data_genera_cupon ws_genera_cupon(string _nombres, string _email, string _dni, int _pordes, int _dias, int _pares_max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bataclub.com.pe/ws_genera_cupon", ReplyAction="*")]
        System.Threading.Tasks.Task<Win_Des_BataClub.ws_bataclub.data_genera_cupon> ws_genera_cuponAsync(string _nombres, string _email, string _dni, int _pordes, int _dias, int _pares_max);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataclub.com.pe/")]
    public partial class Autenticacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string user_passwordField;
        
        private string user_nameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string user_password {
            get {
                return this.user_passwordField;
            }
            set {
                this.user_passwordField = value;
                this.RaisePropertyChanged("user_password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                this.user_nameField = value;
                this.RaisePropertyChanged("user_name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataclub.com.pe/")]
    public partial class data_genera_cupon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cod_errorField;
        
        private string des_errorField;
        
        private string cod_barraField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int cod_error {
            get {
                return this.cod_errorField;
            }
            set {
                this.cod_errorField = value;
                this.RaisePropertyChanged("cod_error");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string des_error {
            get {
                return this.des_errorField;
            }
            set {
                this.des_errorField = value;
                this.RaisePropertyChanged("des_error");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cod_barra {
            get {
                return this.cod_barraField;
            }
            set {
                this.cod_barraField = value;
                this.RaisePropertyChanged("cod_barra");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataclub.com.pe/")]
    public partial class conexion_ws : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cod_errorField;
        
        private string des_errorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int cod_error {
            get {
                return this.cod_errorField;
            }
            set {
                this.cod_errorField = value;
                this.RaisePropertyChanged("cod_error");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string des_error {
            get {
                return this.des_errorField;
            }
            set {
                this.des_errorField = value;
                this.RaisePropertyChanged("des_error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_conexion", WrapperNamespace="http://bataclub.com.pe/", IsWrapped=true)]
    public partial class ws_conexionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://bataclub.com.pe/")]
        public Win_Des_BataClub.ws_bataclub.Autenticacion Autenticacion;
        
        public ws_conexionRequest() {
        }
        
        public ws_conexionRequest(Win_Des_BataClub.ws_bataclub.Autenticacion Autenticacion) {
            this.Autenticacion = Autenticacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_conexionResponse", WrapperNamespace="http://bataclub.com.pe/", IsWrapped=true)]
    public partial class ws_conexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataclub.com.pe/", Order=0)]
        public Win_Des_BataClub.ws_bataclub.conexion_ws ws_conexionResult;
        
        public ws_conexionResponse() {
        }
        
        public ws_conexionResponse(Win_Des_BataClub.ws_bataclub.conexion_ws ws_conexionResult) {
            this.ws_conexionResult = ws_conexionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_BataClubSoapChannel : Win_Des_BataClub.ws_bataclub.WS_BataClubSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_BataClubSoapClient : System.ServiceModel.ClientBase<Win_Des_BataClub.ws_bataclub.WS_BataClubSoap>, Win_Des_BataClub.ws_bataclub.WS_BataClubSoap {
        
        public WS_BataClubSoapClient() {
        }
        
        public WS_BataClubSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_BataClubSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_BataClubSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_BataClubSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Win_Des_BataClub.ws_bataclub.ws_conexionResponse Win_Des_BataClub.ws_bataclub.WS_BataClubSoap.ws_conexion(Win_Des_BataClub.ws_bataclub.ws_conexionRequest request) {
            return base.Channel.ws_conexion(request);
        }
        
        public Win_Des_BataClub.ws_bataclub.conexion_ws ws_conexion(Win_Des_BataClub.ws_bataclub.Autenticacion Autenticacion) {
            Win_Des_BataClub.ws_bataclub.ws_conexionRequest inValue = new Win_Des_BataClub.ws_bataclub.ws_conexionRequest();
            inValue.Autenticacion = Autenticacion;
            Win_Des_BataClub.ws_bataclub.ws_conexionResponse retVal = ((Win_Des_BataClub.ws_bataclub.WS_BataClubSoap)(this)).ws_conexion(inValue);
            return retVal.ws_conexionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Win_Des_BataClub.ws_bataclub.ws_conexionResponse> Win_Des_BataClub.ws_bataclub.WS_BataClubSoap.ws_conexionAsync(Win_Des_BataClub.ws_bataclub.ws_conexionRequest request) {
            return base.Channel.ws_conexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Win_Des_BataClub.ws_bataclub.ws_conexionResponse> ws_conexionAsync(Win_Des_BataClub.ws_bataclub.Autenticacion Autenticacion) {
            Win_Des_BataClub.ws_bataclub.ws_conexionRequest inValue = new Win_Des_BataClub.ws_bataclub.ws_conexionRequest();
            inValue.Autenticacion = Autenticacion;
            return ((Win_Des_BataClub.ws_bataclub.WS_BataClubSoap)(this)).ws_conexionAsync(inValue);
        }
        
        public Win_Des_BataClub.ws_bataclub.data_genera_cupon ws_genera_cupon(string _nombres, string _email, string _dni, int _pordes, int _dias, int _pares_max) {
            return base.Channel.ws_genera_cupon(_nombres, _email, _dni, _pordes, _dias, _pares_max);
        }
        
        public System.Threading.Tasks.Task<Win_Des_BataClub.ws_bataclub.data_genera_cupon> ws_genera_cuponAsync(string _nombres, string _email, string _dni, int _pordes, int _dias, int _pares_max) {
            return base.Channel.ws_genera_cuponAsync(_nombres, _email, _dni, _pordes, _dias, _pares_max);
        }
    }
}
