/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse20025Days
    /// </summary>
    [DataContract]
    public partial class InlineResponse20025Days :  IEquatable<InlineResponse20025Days>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20025Days" /> class.
        /// </summary>
        /// <param name="date">date.</param>
        /// <param name="hardBounce">hardBounce.</param>
        /// <param name="softBounce">softBounce.</param>
        public InlineResponse20025Days(string date = default(string), int? hardBounce = default(int?), int? softBounce = default(int?))
        {
            this.Date = date;
            this.HardBounce = hardBounce;
            this.SoftBounce = softBounce;
        }
        
        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name="Date", EmitDefaultValue=false)]
        public string Date { get; set; }

        /// <summary>
        /// Gets or Sets HardBounce
        /// </summary>
        [DataMember(Name="HardBounce", EmitDefaultValue=false)]
        public int? HardBounce { get; set; }

        /// <summary>
        /// Gets or Sets SoftBounce
        /// </summary>
        [DataMember(Name="SoftBounce", EmitDefaultValue=false)]
        public int? SoftBounce { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20025Days {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  HardBounce: ").Append(HardBounce).Append("\n");
            sb.Append("  SoftBounce: ").Append(SoftBounce).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20025Days);
        }

        /// <summary>
        /// Returns true if InlineResponse20025Days instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20025Days to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20025Days input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.HardBounce == input.HardBounce ||
                    (this.HardBounce != null &&
                    this.HardBounce.Equals(input.HardBounce))
                ) && 
                (
                    this.SoftBounce == input.SoftBounce ||
                    (this.SoftBounce != null &&
                    this.SoftBounce.Equals(input.SoftBounce))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this.HardBounce != null)
                    hashCode = hashCode * 59 + this.HardBounce.GetHashCode();
                if (this.SoftBounce != null)
                    hashCode = hashCode * 59 + this.SoftBounce.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
