/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse20031Days
    /// </summary>
    [DataContract]
    public partial class InlineResponse20031Days :  IEquatable<InlineResponse20031Days>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20031Days" /> class.
        /// </summary>
        /// <param name="date">date.</param>
        /// <param name="_3s">_3s.</param>
        /// <param name="_7s">_7s.</param>
        public InlineResponse20031Days(string date = default(string), int? _3s = default(int?), int? _7s = default(int?))
        {
            this.Date = date;
            this._3s = _3s;
            this._7s = _7s;
        }
        
        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name="Date", EmitDefaultValue=false)]
        public string Date { get; set; }

        /// <summary>
        /// Gets or Sets _3s
        /// </summary>
        [DataMember(Name="3s", EmitDefaultValue=false)]
        public int? _3s { get; set; }

        /// <summary>
        /// Gets or Sets _7s
        /// </summary>
        [DataMember(Name="7s", EmitDefaultValue=false)]
        public int? _7s { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20031Days {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  _3s: ").Append(_3s).Append("\n");
            sb.Append("  _7s: ").Append(_7s).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20031Days);
        }

        /// <summary>
        /// Returns true if InlineResponse20031Days instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20031Days to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20031Days input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this._3s == input._3s ||
                    (this._3s != null &&
                    this._3s.Equals(input._3s))
                ) && 
                (
                    this._7s == input._7s ||
                    (this._7s != null &&
                    this._7s.Equals(input._7s))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this._3s != null)
                    hashCode = hashCode * 59 + this._3s.GetHashCode();
                if (this._7s != null)
                    hashCode = hashCode * 59 + this._7s.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
