//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proy_PruebaMetriCard.ServiceMetricard {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/MetricArts.BataClub.BataPeruService.Data")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTiendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_StringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RegistradoEnFlujosBataClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eMailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTienda {
            get {
                return this.CodigoTiendaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTiendaField, value) != true)) {
                    this.CodigoTiendaField = value;
                    this.RaisePropertyChanged("CodigoTienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((this.DNIField.Equals(value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_String {
            get {
                return this.DNI_StringField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_StringField, value) != true)) {
                    this.DNI_StringField = value;
                    this.RaisePropertyChanged("DNI_String");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fono {
            get {
                return this.FonoField;
            }
            set {
                if ((object.ReferenceEquals(this.FonoField, value) != true)) {
                    this.FonoField = value;
                    this.RaisePropertyChanged("Fono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad {
            get {
                return this.LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadField, value) != true)) {
                    this.LocalidadField = value;
                    this.RaisePropertyChanged("Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RegistradoEnFlujosBataClub {
            get {
                return this.RegistradoEnFlujosBataClubField;
            }
            set {
                if ((this.RegistradoEnFlujosBataClubField.Equals(value) != true)) {
                    this.RegistradoEnFlujosBataClubField = value;
                    this.RaisePropertyChanged("RegistradoEnFlujosBataClub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eMail {
            get {
                return this.eMailField;
            }
            set {
                if ((object.ReferenceEquals(this.eMailField, value) != true)) {
                    this.eMailField = value;
                    this.RaisePropertyChanged("eMail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMetricard.IServicioCliente")]
    public interface IServicioCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EsCliente", ReplyAction="http://tempuri.org/IServicioCliente/EsClienteResponse")]
        bool EsCliente(int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EsCliente", ReplyAction="http://tempuri.org/IServicioCliente/EsClienteResponse")]
        System.Threading.Tasks.Task<bool> EsClienteAsync(int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EsCliente_DniString", ReplyAction="http://tempuri.org/IServicioCliente/EsCliente_DniStringResponse")]
        bool EsCliente_DniString(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EsCliente_DniString", ReplyAction="http://tempuri.org/IServicioCliente/EsCliente_DniStringResponse")]
        System.Threading.Tasks.Task<bool> EsCliente_DniStringAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ObtenerDatosCliente", ReplyAction="http://tempuri.org/IServicioCliente/ObtenerDatosClienteResponse")]
        Proy_PruebaMetriCard.ServiceMetricard.Cliente ObtenerDatosCliente(int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ObtenerDatosCliente", ReplyAction="http://tempuri.org/IServicioCliente/ObtenerDatosClienteResponse")]
        System.Threading.Tasks.Task<Proy_PruebaMetriCard.ServiceMetricard.Cliente> ObtenerDatosClienteAsync(int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ObtenerDatosCliente_DniString", ReplyAction="http://tempuri.org/IServicioCliente/ObtenerDatosCliente_DniStringResponse")]
        Proy_PruebaMetriCard.ServiceMetricard.Cliente ObtenerDatosCliente_DniString(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ObtenerDatosCliente_DniString", ReplyAction="http://tempuri.org/IServicioCliente/ObtenerDatosCliente_DniStringResponse")]
        System.Threading.Tasks.Task<Proy_PruebaMetriCard.ServiceMetricard.Cliente> ObtenerDatosCliente_DniStringAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/IngresarDatosNuevoCliente", ReplyAction="http://tempuri.org/IServicioCliente/IngresarDatosNuevoClienteResponse")]
        Basico_Metricard.ServicioConversion.RespuestaServicio IngresarDatosNuevoCliente(Proy_PruebaMetriCard.ServiceMetricard.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/IngresarDatosNuevoCliente", ReplyAction="http://tempuri.org/IServicioCliente/IngresarDatosNuevoClienteResponse")]
        System.Threading.Tasks.Task<Basico_Metricard.ServicioConversion.RespuestaServicio> IngresarDatosNuevoClienteAsync(Proy_PruebaMetriCard.ServiceMetricard.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarDatosCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarDatosClienteResponse")]
        Basico_Metricard.ServicioConversion.RespuestaServicio ActualizarDatosCliente(Proy_PruebaMetriCard.ServiceMetricard.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarDatosCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarDatosClienteResponse")]
        System.Threading.Tasks.Task<Basico_Metricard.ServicioConversion.RespuestaServicio> ActualizarDatosClienteAsync(Proy_PruebaMetriCard.ServiceMetricard.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EnviarCorreoBienvenidaCliente", ReplyAction="http://tempuri.org/IServicioCliente/EnviarCorreoBienvenidaClienteResponse")]
        Basico_Metricard.ServicioConversion.RespuestaServicio EnviarCorreoBienvenidaCliente(int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EnviarCorreoBienvenidaCliente", ReplyAction="http://tempuri.org/IServicioCliente/EnviarCorreoBienvenidaClienteResponse")]
        System.Threading.Tasks.Task<Basico_Metricard.ServicioConversion.RespuestaServicio> EnviarCorreoBienvenidaClienteAsync(int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EnviarCorreoBienvenidaCliente_DniString", ReplyAction="http://tempuri.org/IServicioCliente/EnviarCorreoBienvenidaCliente_DniStringRespon" +
            "se")]
        Basico_Metricard.ServicioConversion.RespuestaServicio EnviarCorreoBienvenidaCliente_DniString(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EnviarCorreoBienvenidaCliente_DniString", ReplyAction="http://tempuri.org/IServicioCliente/EnviarCorreoBienvenidaCliente_DniStringRespon" +
            "se")]
        System.Threading.Tasks.Task<Basico_Metricard.ServicioConversion.RespuestaServicio> EnviarCorreoBienvenidaCliente_DniStringAsync(string dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioClienteChannel : Proy_PruebaMetriCard.ServiceMetricard.IServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<Proy_PruebaMetriCard.ServiceMetricard.IServicioCliente>, Proy_PruebaMetriCard.ServiceMetricard.IServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EsCliente(int dni) {
            return base.Channel.EsCliente(dni);
        }
        
        public System.Threading.Tasks.Task<bool> EsClienteAsync(int dni) {
            return base.Channel.EsClienteAsync(dni);
        }
        
        public bool EsCliente_DniString(string dni) {
            return base.Channel.EsCliente_DniString(dni);
        }
        
        public System.Threading.Tasks.Task<bool> EsCliente_DniStringAsync(string dni) {
            return base.Channel.EsCliente_DniStringAsync(dni);
        }
        
        public Proy_PruebaMetriCard.ServiceMetricard.Cliente ObtenerDatosCliente(int dni) {
            return base.Channel.ObtenerDatosCliente(dni);
        }
        
        public System.Threading.Tasks.Task<Proy_PruebaMetriCard.ServiceMetricard.Cliente> ObtenerDatosClienteAsync(int dni) {
            return base.Channel.ObtenerDatosClienteAsync(dni);
        }
        
        public Proy_PruebaMetriCard.ServiceMetricard.Cliente ObtenerDatosCliente_DniString(string dni) {
            return base.Channel.ObtenerDatosCliente_DniString(dni);
        }
        
        public System.Threading.Tasks.Task<Proy_PruebaMetriCard.ServiceMetricard.Cliente> ObtenerDatosCliente_DniStringAsync(string dni) {
            return base.Channel.ObtenerDatosCliente_DniStringAsync(dni);
        }
        
        public Basico_Metricard.ServicioConversion.RespuestaServicio IngresarDatosNuevoCliente(Proy_PruebaMetriCard.ServiceMetricard.Cliente cliente) {
            return base.Channel.IngresarDatosNuevoCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<Basico_Metricard.ServicioConversion.RespuestaServicio> IngresarDatosNuevoClienteAsync(Proy_PruebaMetriCard.ServiceMetricard.Cliente cliente) {
            return base.Channel.IngresarDatosNuevoClienteAsync(cliente);
        }
        
        public Basico_Metricard.ServicioConversion.RespuestaServicio ActualizarDatosCliente(Proy_PruebaMetriCard.ServiceMetricard.Cliente cliente) {
            return base.Channel.ActualizarDatosCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<Basico_Metricard.ServicioConversion.RespuestaServicio> ActualizarDatosClienteAsync(Proy_PruebaMetriCard.ServiceMetricard.Cliente cliente) {
            return base.Channel.ActualizarDatosClienteAsync(cliente);
        }
        
        public Basico_Metricard.ServicioConversion.RespuestaServicio EnviarCorreoBienvenidaCliente(int dni) {
            return base.Channel.EnviarCorreoBienvenidaCliente(dni);
        }
        
        public System.Threading.Tasks.Task<Basico_Metricard.ServicioConversion.RespuestaServicio> EnviarCorreoBienvenidaClienteAsync(int dni) {
            return base.Channel.EnviarCorreoBienvenidaClienteAsync(dni);
        }
        
        public Basico_Metricard.ServicioConversion.RespuestaServicio EnviarCorreoBienvenidaCliente_DniString(string dni) {
            return base.Channel.EnviarCorreoBienvenidaCliente_DniString(dni);
        }
        
        public System.Threading.Tasks.Task<Basico_Metricard.ServicioConversion.RespuestaServicio> EnviarCorreoBienvenidaCliente_DniStringAsync(string dni) {
            return base.Channel.EnviarCorreoBienvenidaCliente_DniStringAsync(dni);
        }
    }
}
