/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BatchEmail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BatchEmailTests
    {
        // TODO uncomment below to declare an instance variable for BatchEmail
        //private BatchEmail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BatchEmail
            //instance = new BatchEmail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BatchEmail
        /// </summary>
        [Test]
        public void BatchEmailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BatchEmail
            //Assert.IsInstanceOfType<BatchEmail> (instance, "variable 'instance' is a BatchEmail");
        }


        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Test]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }
        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Test]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'HtmlBody'
        /// </summary>
        [Test]
        public void HtmlBodyTest()
        {
            // TODO unit test for the property 'HtmlBody'
        }
        /// <summary>
        /// Test the property 'TextBody'
        /// </summary>
        [Test]
        public void TextBodyTest()
        {
            // TODO unit test for the property 'TextBody'
        }
        /// <summary>
        /// Test the property 'ReplyTo'
        /// </summary>
        [Test]
        public void ReplyToTest()
        {
            // TODO unit test for the property 'ReplyTo'
        }
        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Test]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }
        /// <summary>
        /// Test the property 'TrackOpens'
        /// </summary>
        [Test]
        public void TrackOpensTest()
        {
            // TODO unit test for the property 'TrackOpens'
        }
        /// <summary>
        /// Test the property 'TrackLinks'
        /// </summary>
        [Test]
        public void TrackLinksTest()
        {
            // TODO unit test for the property 'TrackLinks'
        }
        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Test]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }

    }

}
