/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateInboundRuleTrigger
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateInboundRuleTriggerTests
    {
        // TODO uncomment below to declare an instance variable for CreateInboundRuleTrigger
        //private CreateInboundRuleTrigger instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateInboundRuleTrigger
            //instance = new CreateInboundRuleTrigger();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateInboundRuleTrigger
        /// </summary>
        [Test]
        public void CreateInboundRuleTriggerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateInboundRuleTrigger
            //Assert.IsInstanceOfType<CreateInboundRuleTrigger> (instance, "variable 'instance' is a CreateInboundRuleTrigger");
        }


        /// <summary>
        /// Test the property 'Rule'
        /// </summary>
        [Test]
        public void RuleTest()
        {
            // TODO unit test for the property 'Rule'
        }

    }

}
