/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateTemplateTests
    {
        // TODO uncomment below to declare an instance variable for CreateTemplate
        //private CreateTemplate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateTemplate
            //instance = new CreateTemplate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateTemplate
        /// </summary>
        [Test]
        public void CreateTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateTemplate
            //Assert.IsInstanceOfType<CreateTemplate> (instance, "variable 'instance' is a CreateTemplate");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'TextBody'
        /// </summary>
        [Test]
        public void TextBodyTest()
        {
            // TODO unit test for the property 'TextBody'
        }
        /// <summary>
        /// Test the property 'HtmlBody'
        /// </summary>
        [Test]
        public void HtmlBodyTest()
        {
            // TODO unit test for the property 'HtmlBody'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Test]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }

    }

}
