/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20011Subject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20011SubjectTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20011Subject
        //private InlineResponse20011Subject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20011Subject
            //instance = new InlineResponse20011Subject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20011Subject
        /// </summary>
        [Test]
        public void InlineResponse20011SubjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20011Subject
            //Assert.IsInstanceOfType<InlineResponse20011Subject> (instance, "variable 'instance' is a InlineResponse20011Subject");
        }


        /// <summary>
        /// Test the property 'ContentIsValid'
        /// </summary>
        [Test]
        public void ContentIsValidTest()
        {
            // TODO unit test for the property 'ContentIsValid'
        }
        /// <summary>
        /// Test the property 'ValidationErrors'
        /// </summary>
        [Test]
        public void ValidationErrorsTest()
        {
            // TODO unit test for the property 'ValidationErrors'
        }
        /// <summary>
        /// Test the property 'RenderedContent'
        /// </summary>
        [Test]
        public void RenderedContentTest()
        {
            // TODO unit test for the property 'RenderedContent'
        }

    }

}
