/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20041
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20041Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20041
        //private InlineResponse20041 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20041
            //instance = new InlineResponse20041();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20041
        /// </summary>
        [Test]
        public void InlineResponse20041InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20041
            //Assert.IsInstanceOfType<InlineResponse20041> (instance, "variable 'instance' is a InlineResponse20041");
        }


        /// <summary>
        /// Test the property 'InboundRules'
        /// </summary>
        [Test]
        public void InboundRulesTest()
        {
            // TODO unit test for the property 'InboundRules'
        }
        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Test]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

    }

}
