/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2005Bounces
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2005BouncesTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2005Bounces
        //private InlineResponse2005Bounces instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2005Bounces
            //instance = new InlineResponse2005Bounces();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2005Bounces
        /// </summary>
        [Test]
        public void InlineResponse2005BouncesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2005Bounces
            //Assert.IsInstanceOfType<InlineResponse2005Bounces> (instance, "variable 'instance' is a InlineResponse2005Bounces");
        }


        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Test]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TypeCode'
        /// </summary>
        [Test]
        public void TypeCodeTest()
        {
            // TODO unit test for the property 'TypeCode'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'MessageID'
        /// </summary>
        [Test]
        public void MessageIDTest()
        {
            // TODO unit test for the property 'MessageID'
        }
        /// <summary>
        /// Test the property 'ServerID'
        /// </summary>
        [Test]
        public void ServerIDTest()
        {
            // TODO unit test for the property 'ServerID'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'BouncedAt'
        /// </summary>
        [Test]
        public void BouncedAtTest()
        {
            // TODO unit test for the property 'BouncedAt'
        }
        /// <summary>
        /// Test the property 'DumpAvailable'
        /// </summary>
        [Test]
        public void DumpAvailableTest()
        {
            // TODO unit test for the property 'DumpAvailable'
        }
        /// <summary>
        /// Test the property 'Inactive'
        /// </summary>
        [Test]
        public void InactiveTest()
        {
            // TODO unit test for the property 'Inactive'
        }
        /// <summary>
        /// Test the property 'CanActivate'
        /// </summary>
        [Test]
        public void CanActivateTest()
        {
            // TODO unit test for the property 'CanActivate'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
