/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2008
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2008Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2008
        //private InlineResponse2008 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2008
            //instance = new InlineResponse2008();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2008
        /// </summary>
        [Test]
        public void InlineResponse2008InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2008
            //Assert.IsInstanceOfType<InlineResponse2008> (instance, "variable 'instance' is a InlineResponse2008");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Test]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Test]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

    }

}
