/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20025
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20025Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20025
        //private InlineResponse20025 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20025
            //instance = new InlineResponse20025();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20025
        /// </summary>
        [Test]
        public void InlineResponse20025InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20025
            //Assert.IsInstanceOfType<InlineResponse20025> (instance, "variable 'instance' is a InlineResponse20025");
        }


        /// <summary>
        /// Test the property 'Days'
        /// </summary>
        [Test]
        public void DaysTest()
        {
            // TODO unit test for the property 'Days'
        }
        /// <summary>
        /// Test the property 'HardBounce'
        /// </summary>
        [Test]
        public void HardBounceTest()
        {
            // TODO unit test for the property 'HardBounce'
        }
        /// <summary>
        /// Test the property 'SMTPApiError'
        /// </summary>
        [Test]
        public void SMTPApiErrorTest()
        {
            // TODO unit test for the property 'SMTPApiError'
        }
        /// <summary>
        /// Test the property 'SoftBounce'
        /// </summary>
        [Test]
        public void SoftBounceTest()
        {
            // TODO unit test for the property 'SoftBounce'
        }
        /// <summary>
        /// Test the property 'Transient'
        /// </summary>
        [Test]
        public void TransientTest()
        {
            // TODO unit test for the property 'Transient'
        }

    }

}
