/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20032
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20032Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20032
        //private InlineResponse20032 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20032
            //instance = new InlineResponse20032();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20032
        /// </summary>
        [Test]
        public void InlineResponse20032InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20032
            //Assert.IsInstanceOfType<InlineResponse20032> (instance, "variable 'instance' is a InlineResponse20032");
        }


        /// <summary>
        /// Test the property 'Clicks'
        /// </summary>
        [Test]
        public void ClicksTest()
        {
            // TODO unit test for the property 'Clicks'
        }
        /// <summary>
        /// Test the property 'Days'
        /// </summary>
        [Test]
        public void DaysTest()
        {
            // TODO unit test for the property 'Days'
        }
        /// <summary>
        /// Test the property 'Unique'
        /// </summary>
        [Test]
        public void UniqueTest()
        {
            // TODO unit test for the property 'Unique'
        }

    }

}
