/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20021Opens
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20021OpensTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20021Opens
        //private InlineResponse20021Opens instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20021Opens
            //instance = new InlineResponse20021Opens();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20021Opens
        /// </summary>
        [Test]
        public void InlineResponse20021OpensInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20021Opens
            //Assert.IsInstanceOfType<InlineResponse20021Opens> (instance, "variable 'instance' is a InlineResponse20021Opens");
        }


        /// <summary>
        /// Test the property '_Client'
        /// </summary>
        [Test]
        public void _ClientTest()
        {
            // TODO unit test for the property '_Client'
        }
        /// <summary>
        /// Test the property 'OS'
        /// </summary>
        [Test]
        public void OSTest()
        {
            // TODO unit test for the property 'OS'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Test]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Test]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
        /// <summary>
        /// Test the property 'ReadSeconds'
        /// </summary>
        [Test]
        public void ReadSecondsTest()
        {
            // TODO unit test for the property 'ReadSeconds'
        }
        /// <summary>
        /// Test the property 'Geo'
        /// </summary>
        [Test]
        public void GeoTest()
        {
            // TODO unit test for the property 'Geo'
        }
        /// <summary>
        /// Test the property 'MessageID'
        /// </summary>
        [Test]
        public void MessageIDTest()
        {
            // TODO unit test for the property 'MessageID'
        }
        /// <summary>
        /// Test the property 'ReceivedAt'
        /// </summary>
        [Test]
        public void ReceivedAtTest()
        {
            // TODO unit test for the property 'ReceivedAt'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Test]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }

    }

}
