/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20011ValidationErrors
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20011ValidationErrorsTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20011ValidationErrors
        //private InlineResponse20011ValidationErrors instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20011ValidationErrors
            //instance = new InlineResponse20011ValidationErrors();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20011ValidationErrors
        /// </summary>
        [Test]
        public void InlineResponse20011ValidationErrorsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20011ValidationErrors
            //Assert.IsInstanceOfType<InlineResponse20011ValidationErrors> (instance, "variable 'instance' is a InlineResponse20011ValidationErrors");
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Line'
        /// </summary>
        [Test]
        public void LineTest()
        {
            // TODO unit test for the property 'Line'
        }
        /// <summary>
        /// Test the property 'CharacterPosition'
        /// </summary>
        [Test]
        public void CharacterPositionTest()
        {
            // TODO unit test for the property 'CharacterPosition'
        }

    }

}
