/* 
 * ICOMMKT Transactional API
 *
 * ICOMMKT Transactional API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20034Days
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20034DaysTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20034Days
        //private InlineResponse20034Days instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20034Days
            //instance = new InlineResponse20034Days();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20034Days
        /// </summary>
        [Test]
        public void InlineResponse20034DaysInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20034Days
            //Assert.IsInstanceOfType<InlineResponse20034Days> (instance, "variable 'instance' is a InlineResponse20034Days");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Desktop'
        /// </summary>
        [Test]
        public void DesktopTest()
        {
            // TODO unit test for the property 'Desktop'
        }

    }

}
